# Generated by Django 5.2.7 on 2025-11-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=55)),
                ('tipo', models.CharField(max_length=55)),
                ('alimentacion', models.CharField(max_length=55)),
                ('habitat', models.CharField(max_length=55)),
            ],
        ),
        migrations.DeleteModel(
            name='Deporte',
        ),
    ]
