# Generated by Django 5.2.7 on 2025-11-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_articulo_delete_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
