# Generated by Django 5.2.7 on 2025-11-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
